[project]
name = "poc-xss-django-impersonate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django==4.2.18",
    "django-impersonate==1.9.3",
]
